import styled from '@emotion/native';
import type { LibraryBookResponse, ReadingStatus } from '@where-my-books/shared';
import { AppHeader, ErrorState, LoadingState, PillButton, ScreenContainer, ScreenContent, ScreenScroll, SurfaceCard } from '@where-my-books/ui/native';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { TextInput } from 'react-native';
import { api } from '../../api/client';
const Caption = styled.Text({ color: '#66706B', marginBottom: 12 });
const StatusRow = styled.View({ flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 16 });
const statuses: ReadingStatus[] = ['want_to_read', 'reading', 'finished', 'dnf'];
export default function BookDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const [book, setBook] = useState<LibraryBookResponse | null>(null); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(''); useEffect(() => { if (id) api.book(id).then(setBook).catch((err: unknown) => setError(err instanceof Error ? err.message : 'Ошибка загрузки')); }, [id]); if (error) return <ScreenContainer><ScreenContent><ErrorState message={error} /></ScreenContent></ScreenContainer>; if (!book) return <ScreenContainer><ScreenContent><LoadingState /></ScreenContent></ScreenContainer>; const updateStatus = (status: ReadingStatus) => api.updateStatus(book.id, status).then(setBook); const updatePage = () => { const value = Number(page); if (Number.isInteger(value)) api.updateProgress(book.id, value).then(setBook); }; return <ScreenContainer><ScreenScroll><ScreenContent><AppHeader back title={book.work.title} subtitle={book.work.authors.map((author) => author.name).join(', ')} /><SurfaceCard><Caption>{book.progress.currentPage} / {book.progress.totalPages} страниц · {book.status}</Caption><StatusRow>{statuses.map((status) => <PillButton key={status} label={status} variant={status === book.status ? 'primary' : 'secondary'} onPress={() => updateStatus(status)} />)}</StatusRow><Caption>Изменить текущую страницу</Caption><TextInput value={page} onChangeText={setPage} placeholder={String(book.progress.currentPage)} keyboardType="number-pad" style={{ borderColor: '#D5D9D3', borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 12 }} /><PillButton label="Сохранить прогресс" onPress={updatePage} /></SurfaceCard></ScreenContent></ScreenScroll></ScreenContainer>; }
